# Basic site settings
title: "David DEBRAY CV"
description: "Ingénieur Systèmes & Réseaux - DevOps"
url: "https://davidchdebray.github.io"  # Replace with your GitHub Pages URL
baseurl: ""  # Leave empty for user or organization sites

# Theme configuration
theme: jekyll-theme-minimal

# Markdown processing
markdown: kramdown

# Optional plugins (e.g., RSS feed)
plugins:
  - jekyll-feed
