# Basic site settings
title: "Ingénieur Systèmes & Réseaux - DevOps"
author: "David DEBRAY"
email: "david.debray@pm.me"
description: "David DEBRAY - Curriculum Vitae"
url: "https://davidchdebray.github.io"  # Replace with your GitHub Pages URL
baseurl: ""  # Leave empty for user or organization sites

# theme: jekyll-theme-minimal
# theme: tactile !!
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Markdown processing
markdown: kramdown

kramdown:
  auto_ids: true      # ensures headings get an id automatically
  toc_levels: 1..2     # include headers from h1 to h6 in your TOC


# Optional plugins (e.g., RSS feed)
plugins:
  - jekyll-feed

# Social/contact information (custom variables)
social:
  website: "https://davidchdebray.github.io" 
  email: "mailto:david.debray@pm.me"
  linkedin: "https://www.linkedin.com/in/david-debray-a85b8629/"
  telegram: "https://t.me/@D1d4v"