# File: .github/workflows/build-cv.yml
name: Build CV PDF

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "cv.md"
  pull_request:
    branches: [ master ]
    paths:
      - "cv.md"

jobs:

  show-layout:
    name: 1. Show directory layout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List workspace
        run: |
          echo "→ pwd: $(pwd)"
          ls -R .

  ensure-output:
    name: 2. Ensure output folder exists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make files/ directory
        run: mkdir -p files

  pull-image:
    name: 3. Pull Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Pull pandoc-texlive-full
        run: docker pull ghcr.io/davidchdebray/pandoc-texlive-full:latest

  render-pdf:
    name: 4. Render PDF via Docker
    runs-on: ubuntu-latest
    needs:
      - ensure-output
      - pull-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate DavidDebrayCV.pdf
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/data \
            -w /data \
            ghcr.io/davidchdebray/pandoc-texlive-full:latest \
            --template=./.github/workflows/template.tex \
            --pdf-engine=xelatex \
            cv.md \
            -o files/DavidDebrayCV.pdf

  commit-pdf:
    name: 5. Commit & push updated PDF
    runs-on: ubuntu-latest
    needs: render-pdf
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit & push
        run: |
          git add files/DavidDebrayCV.pdf
          git diff --quiet --exit-code || \
            (git commit -m "ci: auto-update CV PDF [skip ci]" && git push)

