# .github/workflows/build-cv.yml
name: Build CV PDF

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'cv.md'
  pull_request:
    branches: [ master ]
    paths:
      - 'cv.md'

jobs:
  build:
    name: Generate & Upload CV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show directory layout
        run: |
          echo "→ pwd: $(pwd)"
          echo "→ files in repo:"
          ls -R .

      - name: Ensure output folder
        run: mkdir -p files

      - name: Pull pandoc-texlive container
        run: docker pull ghcr.io/davidchdebray/pandoc-texlive-full:latest

      - name: Render PDF via Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/data \
            -w /data \
            ghcr.io/davidchdebray/pandoc-texlive-full:latest \
            --template=./.github/workflows/template.tex \
            --pdf-engine=xelatex \
            cv.md \
            -o files/DavidDebrayCV.pdf

      - name: Upload CV.pdf
        uses: actions/upload-artifact@v3
        with:
          name: CV.pdf
          path: files/DavidDebrayCV.pdf