# File: .github/workflows/build-cv.yml
name: Build CV PDF

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "cv.md"
  pull_request:
    branches: [ master ]
    paths:
      - "cv.md"

jobs:

  checkout:
    name: 1. Checkout repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  generate-pdf:
    name: 2. Generate DavidDebrayCV.pdf
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Pull pandoc-texlive-full image
        run: docker pull ghcr.io/davidchdebray/pandoc-texlive-full:latest

      - name: Ensure output directory exists
        run: mkdir -p files

      - name: Render PDF via Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/data \
            -w /data \
            ghcr.io/davidchdebray/pandoc-texlive-full:latest \
            cv.md \
            --template=.github/workflows/template.tex \
            --pdf-engine=xelatex \
            -o files/DavidDebrayCV.pdf

  upload-artifact:
    name: 3. Upload PDF artifact
    runs-on: ubuntu-latest
    needs: generate-pdf
    steps:
      - name: Upload DavidDebrayCV.pdf
        uses: actions/upload-artifact@v3
        with:
          name: DavidDebrayCV.pdf
          path: files/DavidDebrayCV.pdf
