# .github/workflows/build-cv.yml
name: Build CV PDF

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "cv.md"
  pull_request:
    branches: [ master ]
    paths:
      - "cv.md"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  install:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install xelatex
        run: sudo apt-get install -y texlive-xetex

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build PDF
        run: pandoc cv.md --template=.github/workflows/template.tex --pdf-engine=xelatex -o files/DavidDebrayCV.pdf