# File: .github/workflows/build-cv.yml
name: Build CV PDF

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:  
      - 'cv.md'
  pull_request:
    branches: [ master ]
    paths:  
      - 'cv.md'

jobs:
  checkout:
    name: 1. Checkout Repository
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build-image:
    name: 2. Build Docker Image
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Build cv-builder image
        run: |
          docker build . \
            -t cv-builder:latest

  generate-pdf:
    name: 3. Generate DavidDebrayCV.pdf
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Ensure output directory exists
        run: mkdir -p files

      - name: Run pandoc inside the container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/data \
            -w /data \
            ghcr.io/davidchdebray/pandoc-texlive-full:latest \
            cv.md \
            --template=.github/workflows/template.tex \
            --pdf-engine=xelatex \
            -o files/DavidDebrayCV.pdf

  upload-artifact:
    name: 4. Upload PDF Artifact
    runs-on: ubuntu-latest
    needs: generate-pdf
    steps:
      - name: Upload DavidDebrayCV.pdf
        uses: actions/upload-artifact@v3
        with:
          name: DavidDebrayCV.pdf
          path: files/DavidDebrayCV.pdf
