# File: .github/workflows/build-cv.yml
name: Build CV PDF

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'cv.md'
  pull_request:
    branches: [ master ]
    paths:
      - 'cv.md'

jobs:

  checkout:
    name: 1. Checkout repository
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  show-layout:
    name: 2. Show directory layout
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: List all files
        run: |
          echo "Working directory: ${{ needs.checkout.outputs.repo-path }}"
          ls -R ${{ needs.checkout.outputs.repo-path }}

  ensure-output:
    name: 3. Ensure output folder exists
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Create files/ directory
        run: mkdir -p ${{ needs.checkout.outputs.repo-path }}/files

  pull-image:
    name: 4. Pull Docker image
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: docker pull pandoc-texlive-full
        run: docker pull ghcr.io/davidchdebray/pandoc-texlive-full:latest

  render-pdf:
    name: 5. Render PDF via Docker
    runs-on: ubuntu-latest
    needs:
      - ensure-output
      - pull-image
    steps:
      - name: Render DavidDebrayCV.pdf
        run: |
          docker run --rm \
            -v "${{ needs.checkout.outputs.repo-path }}":/data \
            -w /data \
            ghcr.io/davidchdebray/pandoc-texlive-full:latest \
            --template=./.github/workflows/template.tex \
            --pdf-engine=xelatex \
            cv.md \
            -o files/DavidDebrayCV.pdf

  upload-artifact:
    name: 6. Upload CV artifact
    runs-on: ubuntu-latest
    needs: render-pdf
    steps:
      - name: Upload DavidDebrayCV.pdf
        uses: actions/upload-artifact@v4
        with:
          name: DavidDebrayCV.pdf
          path: files/DavidDebrayCV.pdf
