name: Build CV PDF (fast)

on:
  push:
    paths: ['cv.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jakejarvis/tinytex:latest   # pre‑installed TinyTeX
    steps:
      - uses: actions/checkout@v4

      - name: Install latest Pandoc
        run: |
          wget -qO- https://github.com/jgm/pandoc/releases/download/3.5/pandoc-3.5-linux-amd64.tar.gz |
          tar xz --strip-components=1 -C /usr/local bin/pandoc
          chmod +x /usr/local/bin/pandoc

      - name: Build PDF
        run: |
          mkdir -p files
          pandoc cv.md \
            --template=.github/workflows/template.tex \
            --pdf-engine=xelatex \
            -o files/DavidDebrayCV.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: DavidDebrayCV
          path: files/DavidDebrayCV.pdf