name: Build CV PDF – separate jobs (uses pre‑built container)

# -------------------------------------------------
# When to run the workflow
# -------------------------------------------------
on:
  push:
    paths:
      - 'cv.md'               # rebuild whenever the markdown source changes
  workflow_dispatch:          # manual trigger from the UI

# -------------------------------------------------
# 1️⃣ Checkout job – fetches the repo (kept for symmetry)
# -------------------------------------------------
jobs:
  checkout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

# -------------------------------------------------
# 2️⃣ Build job – runs inside the custom Docker image
# -------------------------------------------------
  build:
    runs-on: ubuntu-latest
    needs: checkout
    permissions:
      contents: read
    container:
      image: ghcr.io/davidchdebray/pandoc-texlive-full:latest
      options: --user root               # run as root so we can write anywhere
    steps:
      # The repository isn’t automatically present inside the container,
      # so we check it out again.
      - name: Checkout repository again
        uses: actions/checkout@v4

      - name: Create output folder
        run: mkdir -p files               # <-- this folder maps to /files/ on the site

      - name: Convert markdown → PDF with Pandoc
        run: |
          pandoc cv.md \
            --template=.github/workflows/template.tex \
            --pdf-engine=xelatex \
            -o files/DavidDebrayCV.pdf

# -------------------------------------------------
# 3️⃣ Artifact job – makes the PDF available to the next job
# -------------------------------------------------
  artifact:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - name: Checkout repository again
        uses: actions/checkout@v4

      - name: Upload PDF as a workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: DavidDebrayCV
          path: files/DavidDebrayCV.pdf

# -------------------------------------------------
# 4️⃣ Publish job – pushes the PDF to the **master** branch
# -------------------------------------------------
  publish:
    runs-on: ubuntu-latest
    needs: artifact
    permissions:
      contents: write               # needed to push a commit
    steps:
      # 1️⃣ Checkout the master branch that GitHub Pages builds from
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master               # <-- your site’s source branch
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0            # full history – avoids shallow‑clone fetch errors

      # 2️⃣ Pull the PDF artifact we just created
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: DavidDebrayCV
          path: ./files             # matches the URL path (/files/…)

      # 3️⃣ Ensure the target folder exists (defensive)
      - name: Ensure target folder exists
        run: mkdir -p files

      # 4️⃣ Stage, commit, and push the new PDF (only if it changed)
      - name: Commit and push PDF
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          # Force‑add the PDF in case the path is ignored by .gitignore
          git add -f files/DavidDebrayCV.pdf
          if ! git diff --cached --quiet; then
            git commit -m "Update CV PDF (auto‑generated)"
            git push origin master
          else
            echo "PDF unchanged – nothing to push."
          fi