# .github/workflows/build-cv.yml
name: Build CV PDF

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "cv.md"
  pull_request:
    branches: [ master ]
    paths:
      - "cv.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Running system update
        run: sudo apt-get update

      - name: Install requirements
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex texlive-fonts-extra
        
      - name: Build PDF
        run: pandoc cv.md --template=.github/workflows/template.tex --pdf-engine=xelatex -o files/DavidDebrayCV.pdf