# .github/workflows/build-cv.yml
name: Build CV PDF

on:
  workflow_dispatch:

  push:
    branches: [ master ]
    paths:
      - "cv.md"

  pull_request:
    branches: [ master ]
    paths:
      - "cv.md"

jobs:

  checkout:
    name: 1. Checkout repository
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  ensure-output:
    name: 2. Ensure output folder
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - name: Create files/ dir
        run: mkdir -p files

  pull-image:
    name: 3. Pull Docker image
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Pull pandoc-texlive-full
        run: docker pull ghcr.io/davidchdebray/pandoc-texlive-full:latest

  render-pdf:
    name: 4. Render PDF via Docker
    runs-on: ubuntu-latest
    needs:
      - ensure-output
      - pull-image
    steps:
      - uses: actions/checkout@v4
      - name: Generate DavidDebrayCV.pdf
        run: |
          docker run --rm \
            -v "${{ needs.checkout.outputs.repo-path }}":/data \
            -w /data \
            ghcr.io/davidchdebray/pandoc-texlive-full:latest \
            --template=./.github/workflows/template.tex \
            --pdf-engine=xelatex \
            cv.md \
            -o files/DavidDebrayCV.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: files/DavidDebrayCV.pdf

  commit-pdf:
    name: 5. Commit & Push updated PDF
    runs-on: ubuntu-latest
    needs: render-pdf
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Download generated PDF
        uses: actions/download-artifact@v4
        with:
          name: cv-pdf
          path: .

      - name: Place PDF into files/
        run: |
          mkdir -p files
          mv DavidDebrayCV.pdf files/DavidDebrayCV.pdf

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit & push if changed
        run: |
          git add files/DavidDebrayCV.pdf
          git diff --quiet --exit-code || \
            (git commit -m "ci: auto-update CV PDF [skip ci]" && git push)
